module.exports = {
  appId: 'com.roachwares.roachnet.setup',
  productName: 'RoachNet Setup',
  asar: true,
  asarUnpack: [
    'scripts/**/*',
    'setup-ui/**/*',
    'admin/**/*',
    'docs/**/*',
    'README.md',
      ],
  directories: {
    buildResources: 'desktop/assets',
    output: 'setup-dist',
  },
  extraMetadata: {
    main: 'installer/main.cjs',
    name: 'roachnet-setup',
    productName: 'RoachNet Setup',
  },
  generateUpdatesFilesForAllChannels: false,
  electronUpdaterCompatibility: '>=2.16',
  files: [
    'installer/**/*',
    'desktop/assets/**/*',
    'desktop/config.cjs',
    'scripts/**/*',
    'setup-ui/**/*',
    'admin/**/*',
    'docs/**/*',
    'README.md',
        'package.json',
    '!admin/node_modules{,/**/*}',
    '!admin/node_modules_node25_partial_20260327{,/**/*}',
    '!admin/storage/logs{,/**/*}',
    '!admin/storage/tmp{,/**/*}',
    '!desktop-dist{,/**/*}',
    '!setup-dist{,/**/*}',
    '!desktop/setup_*{,/**/*}',
    '!desktop/setup_renderer{,/**/*}',
    '!.git{,/**/*}',
    '!node_modules/.cache{,/**/*}',
  ],
  mac: {
    category: 'public.app-category.utilities',
    target: ['dmg', 'zip'],
    icon: 'desktop/assets/icon.icns',
    artifactName: 'RoachNet-Setup-${version}-mac-${arch}.${ext}',
  },
  win: {
    target: ['nsis', 'portable'],
    icon: 'desktop/assets/icon.ico',
    artifactName: 'RoachNet-Setup-${version}-win-${arch}.${ext}',
  },
  linux: {
    target: ['AppImage', 'deb', 'rpm'],
    icon: 'desktop/assets/icon.png',
    artifactName: 'RoachNet-Setup-${version}-linux-${arch}.${ext}',
    category: 'Utility',
  },
}
